#pragma once

#include <directx/d3d12.h>
#include <stdexcept>
#include <spdlog/spdlog.h>
#if defined(_DEBUG)
#include <string>
#endif // _DEBUG
#include <set>


class Resource;

inline const char* BarrierLayoutToString(D3D12_BARRIER_LAYOUT layout)
{
	switch (layout)
	{
	case D3D12_BARRIER_LAYOUT_UNDEFINED:                    return "UNDEFINED";
	case D3D12_BARRIER_LAYOUT_COMMON:                       return "COMMON";
	//case D3D12_BARRIER_LAYOUT_PRESENT:                      return "PRESENT";
	case D3D12_BARRIER_LAYOUT_GENERIC_READ:                 return "GENERIC_READ";
	case D3D12_BARRIER_LAYOUT_RENDER_TARGET:                return "RENDER_TARGET";
	case D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS:             return "UNORDERED_ACCESS";
	case D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE:          return "DEPTH_STENCIL_WRITE";
	case D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ:           return "DEPTH_STENCIL_READ";
	case D3D12_BARRIER_LAYOUT_SHADER_RESOURCE:              return "SHADER_RESOURCE";
	case D3D12_BARRIER_LAYOUT_COPY_SOURCE:                  return "COPY_SOURCE";
	case D3D12_BARRIER_LAYOUT_COPY_DEST:                    return "COPY_DEST";
	case D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE:               return "RESOLVE_SOURCE";
	case D3D12_BARRIER_LAYOUT_RESOLVE_DEST:                 return "RESOLVE_DEST";
	case D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE:          return "SHADING_RATE_SOURCE";
	case D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ:            return "VIDEO_DECODE_READ";
	case D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE:           return "VIDEO_DECODE_WRITE";
	case D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ:           return "VIDEO_PROCESS_READ";
	case D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE:          return "VIDEO_PROCESS_WRITE";
	case D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ:            return "VIDEO_ENCODE_READ";
	case D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE:           return "VIDEO_ENCODE_WRITE";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON:          return "DIRECT_QUEUE_COMMON";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ:    return "DIRECT_QUEUE_GENERIC_READ";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS:return "DIRECT_QUEUE_UNORDERED_ACCESS";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE: return "DIRECT_QUEUE_SHADER_RESOURCE";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE:     return "DIRECT_QUEUE_COPY_SOURCE";
	case D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST:       return "DIRECT_QUEUE_COPY_DEST";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON:         return "COMPUTE_QUEUE_COMMON";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ:   return "COMPUTE_QUEUE_GENERIC_READ";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS:return "COMPUTE_QUEUE_UNORDERED_ACCESS";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE:return "COMPUTE_QUEUE_SHADER_RESOURCE";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE:    return "COMPUTE_QUEUE_COPY_SOURCE";
	case D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST:      return "COMPUTE_QUEUE_COPY_DEST";
	case D3D12_BARRIER_LAYOUT_VIDEO_QUEUE_COMMON:           return "VIDEO_QUEUE_COMMON";
	default:                                                return "UNKNOWN";
	}
}

inline const char* BarrierAccessToString(D3D12_BARRIER_ACCESS access)
{
	switch (access)
	{
	case D3D12_BARRIER_ACCESS_COMMON:                               return "COMMON";
	case D3D12_BARRIER_ACCESS_VERTEX_BUFFER:                        return "VERTEX_BUFFER";
	case D3D12_BARRIER_ACCESS_CONSTANT_BUFFER:                      return "CONSTANT_BUFFER";
	case D3D12_BARRIER_ACCESS_INDEX_BUFFER:                         return "INDEX_BUFFER";
	case D3D12_BARRIER_ACCESS_RENDER_TARGET:                        return "RENDER_TARGET";
	case D3D12_BARRIER_ACCESS_UNORDERED_ACCESS:                     return "UNORDERED_ACCESS";
	case D3D12_BARRIER_ACCESS_DEPTH_STENCIL_WRITE:                  return "DEPTH_STENCIL_WRITE";
	case D3D12_BARRIER_ACCESS_DEPTH_STENCIL_READ:                   return "DEPTH_STENCIL_READ";
	case D3D12_BARRIER_ACCESS_SHADER_RESOURCE:                      return "SHADER_RESOURCE";
	case D3D12_BARRIER_ACCESS_STREAM_OUTPUT:                        return "STREAM_OUTPUT";
	case D3D12_BARRIER_ACCESS_INDIRECT_ARGUMENT:                    return "INDIRECT_ARGUMENT";
	//case D3D12_BARRIER_ACCESS_PREDICATION:                          return "PREDICATION"; // ?
	case D3D12_BARRIER_ACCESS_COPY_DEST:                            return "COPY_DEST";
	case D3D12_BARRIER_ACCESS_COPY_SOURCE:                          return "COPY_SOURCE";
	case D3D12_BARRIER_ACCESS_RESOLVE_DEST:                         return "RESOLVE_DEST";
	case D3D12_BARRIER_ACCESS_RESOLVE_SOURCE:                       return "RESOLVE_SOURCE";
	case D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_READ: return "RAYTRACING_ACCELERATION_STRUCTURE_READ";
	case D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_WRITE: return "RAYTRACING_ACCELERATION_STRUCTURE_WRITE";
	case D3D12_BARRIER_ACCESS_SHADING_RATE_SOURCE:                  return "SHADING_RATE_SOURCE";
	case D3D12_BARRIER_ACCESS_VIDEO_DECODE_READ:                    return "VIDEO_DECODE_READ";
	case D3D12_BARRIER_ACCESS_VIDEO_DECODE_WRITE:                   return "VIDEO_DECODE_WRITE";
	case D3D12_BARRIER_ACCESS_VIDEO_PROCESS_READ:                   return "VIDEO_PROCESS_READ";
	case D3D12_BARRIER_ACCESS_VIDEO_PROCESS_WRITE:                  return "VIDEO_PROCESS_WRITE";
	case D3D12_BARRIER_ACCESS_VIDEO_ENCODE_READ:                    return "VIDEO_ENCODE_READ";
	case D3D12_BARRIER_ACCESS_VIDEO_ENCODE_WRITE:                   return "VIDEO_ENCODE_WRITE";
	case D3D12_BARRIER_ACCESS_NO_ACCESS:                            return "NO_ACCESS";
	default:                                                        return "UNKNOWN";
	}
}

inline const char* BarrierSyncToString(D3D12_BARRIER_SYNC sync)
{
	switch (sync)
	{
	case D3D12_BARRIER_SYNC_NONE:       return "NONE";
	case D3D12_BARRIER_SYNC_ALL:        return "ALL";
	case D3D12_BARRIER_SYNC_DRAW:       return "DRAW";
	case D3D12_BARRIER_SYNC_INDEX_INPUT:return "INDEX_INPUT";
	case D3D12_BARRIER_SYNC_VERTEX_SHADING: return "VERTEX_SHADING";
	case D3D12_BARRIER_SYNC_PIXEL_SHADING:  return "PIXEL_SHADING";
	case D3D12_BARRIER_SYNC_DEPTH_STENCIL:  return "DEPTH_STENCIL";
	case D3D12_BARRIER_SYNC_RENDER_TARGET:  return "RENDER_TARGET";
	case D3D12_BARRIER_SYNC_COMPUTE_SHADING:return "COMPUTE_SHADING";
	case D3D12_BARRIER_SYNC_RAYTRACING:     return "RAYTRACING";
	case D3D12_BARRIER_SYNC_COPY:           return "COPY";
	case D3D12_BARRIER_SYNC_RESOLVE:        return "RESOLVE";
	case D3D12_BARRIER_SYNC_EXECUTE_INDIRECT:return "EXECUTE_INDIRECT";
	//case D3D12_BARRIER_SYNC_PREDICATION:    return "PREDICATION";
	case D3D12_BARRIER_SYNC_ALL_SHADING:    return "ALL_SHADING";
	case D3D12_BARRIER_SYNC_NON_PIXEL_SHADING: return "NON_PIXEL_SHADING";
	case D3D12_BARRIER_SYNC_EMIT_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO:
		return "EMIT_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO";
	case D3D12_BARRIER_SYNC_CLEAR_UNORDERED_ACCESS_VIEW:
		return "CLEAR_UNORDERED_ACCESS_VIEW";
	case D3D12_BARRIER_SYNC_VIDEO_DECODE:   return "VIDEO_DECODE";
	case D3D12_BARRIER_SYNC_VIDEO_PROCESS:  return "VIDEO_PROCESS";
	case D3D12_BARRIER_SYNC_VIDEO_ENCODE:   return "VIDEO_ENCODE";
	case D3D12_BARRIER_SYNC_BUILD_RAYTRACING_ACCELERATION_STRUCTURE:
		return "BUILD_RAYTRACING_ACCELERATION_STRUCTURE";
	case D3D12_BARRIER_SYNC_COPY_RAYTRACING_ACCELERATION_STRUCTURE:
		return "COPY_RAYTRACING_ACCELERATION_STRUCTURE";
	case D3D12_BARRIER_SYNC_SPLIT:          return "SPLIT";
	default:                                return "UNKNOWN";
	}
}
