#ifndef __BLOOM_DOWNSAMPLE_ROOT_CONSTANTS_H__
#define __BLOOM_DOWNSAMPLE_ROOT_CONSTANTS_H__

#define MIP_INDEX UintRootConstant0
#define MIP_WIDTH UintRootConstant1
#define MIP_HEIGHT UintRootConstant2

#define SRC_TEXEL_SIZE_X FloatRootConstant0
#define SRC_TEXEL_SIZE_Y FloatRootConstant1
#define FILTER_RADIUS FloatRootConstant2
#define ASPECT_RATIO FloatRootConstant3

#endif // __BLOOM_DOWNSAMPLE_ROOT_CONSTANTS_H__