#ifndef __CONSTANTS_HLSLI__
#define __CONSTANTS_HLSLI__

#define PI 3.1415926538

#define SH_FLOAT_SCALE 100 // 1<<20
#define SH_FLOAT_SCALE_INVERSE 1.0f / SH_FLOAT_SCALE

#endif //__CONSTANTS_HLSLI__