#ifndef __MATERIALFLAGS_HLSL_
#define __MATERIALFLAGS_HLSL_

#define MATERIAL_TEXTURED 1 << 0
#define MATERIAL_BASE_COLOR_TEXTURE 1 << 1
#define MATERIAL_NORMAL_MAP 1 << 2
#define MATERIAL_AO_TEXTURE 1 << 3
#define MATERIAL_EMISSIVE_TEXTURE 1 << 4
#define MATERIAL_PBR 1 << 5
#define MATERIAL_PBR_MAPS 1 << 6
#define MATERIAL_DOUBLE_SIDED 1 << 7
#define MATERIAL_PARALLAX 1 << 8

#endif // __MATERIALFLAGS_HLSL_